name: aspire
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - array-api-compat
  - bilby>=2.6.0
  - bilby_pipe>=1.6.0
  - dynesty
  - emcee
  - pesummary
  - zuko
  - natsort
  - pytest
  - pytest-requires
  - pytorch-cpu
  - wrapt
  - jax
  - optax
  - jaxlib
  - chex
  - equinox
  - toolz
  - jaxtyping
  - wadler-lindig
  - pip
  - pip:
    - flowjax
