title: Analysis with aspire
author: Michael J. Williams

execute:
  execute_notebooks: force

repository:
  url: https://github.com/mj-will/aspire-analyses
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  show_sidebar: true
  sidebar:
    toc_depth: 3